name: build-windows
on: [workflow_dispatch]
jobs:
  build:
    runs-on: windows-2019

    steps:

    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: '0'

    - name: setup mkl venv
      if: runner.os == 'Windows'
      run: python source/scripts/install_mkl.py

    - name: Build externals on Windows
      if: runner.os == 'Windows'
      run: |
        cd build
        cmake ..
        cmake --build . --config Release

    - uses: actions/upload-artifact@v4
      with:
        name: aharker-win64-externals
        path: |
            docs
            externals
            help
            misc
            LICENSE
            README.md
