name: build-windows-make
on: [workflow_dispatch]
jobs:
  build:
    runs-on: windows-2019

    steps:

    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: '0'

    - name: build with make
      run: make windows

    - uses: actions/upload-artifact@v4
      with:
        name: aharker-win64-externals
        path: |
            docs
            externals
            help
            misc
            LICENSE
            README.md
