name: build-macos
on: [workflow_dispatch]
jobs:
  build:
    runs-on: macos-14

    steps:

    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: '0'

    - name: Build externals
      run: |
        mkdir -p build
        cd build
        cmake .. -GXcode
        cmake --build . --config Release

    - uses: actions/upload-artifact@v4
      with:
        name: aharker-macos-externals
        path: |
            docs
            externals
            help
            misc
            LICENSE
            README.md
